### ISSUE TITLE
Error when login in - Headers is not defined

### ISSUE THREAD

**Issue by Ooin** [mateussouzaweb/crunchyroll-webos#37] opened 2024-02-01 16:22 UTC
Hi
after installing the I try to log in with the right user and password and the screen displays the error _Headers is not defined_ and doesn't log in.

**Comment by mateussouzaweb** [comment] 2024-02-06 23:08
@Ooin what WebOS version is your tv?

**Comment by Ooin** [comment] 2024-02-07 12:07
> @Ooin what WebOS version is your tv?

Hi, I'm in the v4.3.5

**Comment by henrique-eba** [comment] 2024-02-07 17:08
Hey,

I'm on 06.10.30 (webOS TV OLED65B7V).

**Comment by throwaway96** [comment] 2024-02-08 21:57
@Ooin

> Hi, I'm in the v4.3.5

I'm pretty sure there was never a webOS 4.3.5. You may be looking at the firmware version ("software version") rather than the webOS version. What model is your TV?

The reason I'm asking is that you may be able to really help us out. If you actually meant version 04.30.05, the only firmware I know of with that version is for a model we don't have the [firmware key](https://github.com/throwaway96/epk2extract/blob/master/keys/AES.key) for yet.

**Comment by Ooin** [comment] 2024-02-09 08:10
> @Ooin
> 
> > Hi, I'm in the v4.3.5
> 
> I'm pretty sure there was never a webOS 4.3.5. You may be looking at the firmware version ("software version") rather than the webOS version. What model is your TV?
> 
> The reason I'm asking is that you may be able to really help us out. If you actually meant version 04.30.05, the only firmware I know of with that version is for a model we don't have the [firmware key](https://github.com/throwaway96/epk2extract/blob/master/keys/AES.key) for yet.

You are right, I'm on 06.10.50
The TV being a 43UJ701V-ZV

**Comment by Lostkep** [comment] 2024-02-10 10:34
I got the same problem using WebOS 06.10.50 on UJ6309

**Comment by mateussouzaweb** [comment] 2024-02-10 13:22
New adjustments were made to fix that bug. 

Can someone please download and install the test version available in the run artifacts just to make sure this is what we need? https://github.com/mateussouzaweb/crunchyroll-webos/actions/runs/7855041666

**Comment by Lostkep** [comment] 2024-02-10 19:09
I installed the Snapshot, now im getting the error "undefined is not a function" when hitting the Login Button

**Comment by mateussouzaweb** [comment] 2024-02-11 18:30
@Lostkep can you try this new build? https://github.com/mateussouzaweb/crunchyroll-webos/actions/runs/7863870354
This won't fix the problem, but hopefully we will get more details about the error when you reproduce it again...

**Comment by ivanch4** [comment] 2024-02-12 19:57
Hi @mateussouzaweb I'm on software version 06.10.30 and I'm also getting the same error. Testing the new build, I get Undefined is not a function, and then the following errors:

https://photos.app.goo.gl/ZPScJisgFtgWhDis5

**Comment by mateussouzaweb** [comment] 2024-02-12 21:03
OK, this is very odd... ``String.includes`` is available since Chromium 41. WebOS 4.x runs with Chromium 53, so it feels like you are running WebOS 3.x... The main issue in this card also suggests that something is not correct with these WebOS versions... please check again what version is your TV:

Settings > General > TV Information > webOS TV version

Also, I submitted new updates, hopefully you will login now!
https://github.com/mateussouzaweb/crunchyroll-webos/actions/runs/7877686491

**Comment by ivanch4** [comment] 2024-02-12 21:14
You were right regarding the WebOS version; it is 3.9.2-6270908 (OLED55B7T) Fortunately, I was able to login and stream videos using your latest test version. Thank you!

**Closed** 2024-02-13 01:29 UTC
Labels: bug
